// @generated by AI Unit Test Agent -- review before merging
import React from 'react';
import { render, screen } from '@testing-library/react';
import '@testing-library/jest-dom';
import MovieCard from './MovieCard';

const baseMovie = {
  title: 'Inception',
  vote_average: 8.19,
  poster_path: '/abc123.jpg',
  release_date: '2021-07-16',
  original_language: 'en',
};

describe('MovieCard', () => {
  it('should render the title, rating, language and year for a full movie object', () => {
    const { container } = render(<MovieCard movie={baseMovie} />);

    expect(
      screen.getByRole('heading', { level: 3, name: /Inception/ })
    ).toBeInTheDocument();
    expect(screen.getByText('8.2')).toBeInTheDocument();

    const lang = container.querySelector('.lang');
    expect(lang).toHaveTextContent('en');

    const year = container.querySelector('.year');
    expect(year).toHaveTextContent('2021');
  });

  it('should build the poster URL from poster_path and use title as alt text', () => {
    render(<MovieCard movie={baseMovie} />);
    const poster = screen.getByRole('img', { name: 'Inception' });
    expect(poster).toHaveAttribute(
      'src',
      'https://image.tmdb.org/t/p/w500//abc123.jpg'
    );
  });

  it.each([
    ['null', null],
    ['undefined', undefined],
  ])('should fall back to /no-movie.png when poster_path is %s', (_label, value) => {
    render(<MovieCard movie={{ ...baseMovie, poster_path: value }} />);
    const poster = screen.getByRole('img', { name: 'Inception' });
    expect(poster).toHaveAttribute('src', '/no-movie.png');
  });

  it.each([
    ['undefined', undefined],
    ['null', null],
    ['0', 0],
  ])('should show N/A for rating when vote_average is %s', (_label, value) => {
    const { container } = render(
      <MovieCard movie={{ ...baseMovie, vote_average: value }} />
    );
    const ratingText = container.querySelector('.rating p');
    expect(ratingText).toHaveTextContent('N/A');
  });

  it('should format the rating to one decimal place', () => {
    const { container, rerender } = render(
      <MovieCard movie={{ ...baseMovie, vote_average: 7 }} />
    );
    expect(container.querySelector('.rating p')).toHaveTextContent('7.0');

    const expected = (6.25).toFixed(1);
    rerender(<MovieCard movie={{ ...baseMovie, vote_average: 6.25 }} />);
    expect(container.querySelector('.rating p')).toHaveTextContent(expected);
  });

  it.each([
    ['undefined', undefined],
    ['an empty string', ''],
  ])('should show N/A for the year when release_date is %s', (_label, value) => {
    const { container } = render(
      <MovieCard movie={{ ...baseMovie, release_date: value }} />
    );
    expect(container.querySelector('.year')).toHaveTextContent('N/A');
  });

  it('should display only the year part of a release_date', () => {
    const { container } = render(
      <MovieCard movie={{ ...baseMovie, release_date: '1999-03-31' }} />
    );
    const year = container.querySelector('.year');
    expect(year).toHaveTextContent('1999');
    expect(year.textContent).toBe('1999');
    expect(screen.queryByText('1999-03-31')).not.toBeInTheDocument();
  });

  it('should always render the star icon with alt text', () => {
    render(<MovieCard movie={baseMovie} />);
    const star = screen.getByRole('img', { name: 'Star Icon' });
    expect(star).toBeInTheDocument();
    expect(star).toHaveAttribute('src', 'star.svg');
  });

  it('should render two bullet separators between rating, language and year', () => {
    render(<MovieCard movie={baseMovie} />);
    expect(screen.getAllByText('•')).toHaveLength(2);
  });

  it('should throw when the movie prop is not provided', () => {
    const spy = jest.spyOn(console, 'error').mockImplementation(() => {});
    expect(() => render(<MovieCard />)).toThrow(TypeError);
    spy.mockRestore();
  });
});