// @generated by AI Unit Test Agent -- review before merging
import React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import '@testing-library/jest-dom';
import Search from './Search';

describe('Search', () => {
  let setSearchTerm;

  beforeEach(() => {
    setSearchTerm = jest.fn();
  });

  it('should render the search input with its placeholder', () => {
    render(<Search searchTerm="" setSearchTerm={setSearchTerm} />);
    const input = screen.getByPlaceholderText('Search through thousands of movies');
    expect(input).toBeInTheDocument();
    expect(input).toHaveAttribute('type', 'text');
  });

  it('should render the search icon image with alt text', () => {
    render(<Search searchTerm="" setSearchTerm={setSearchTerm} />);
    const img = screen.getByAltText('search');
    expect(img).toBeInTheDocument();
    expect(img).toHaveAttribute('src', 'search.svg');
  });

  it('should display the searchTerm prop as the input value', () => {
    render(<Search searchTerm="batman" setSearchTerm={setSearchTerm} />);
    expect(screen.getByPlaceholderText('Search through thousands of movies')).toHaveValue('batman');
  });

  it('should call setSearchTerm with the typed value when the user types', async () => {
    const user = userEvent.setup();
    render(<Search searchTerm="" setSearchTerm={setSearchTerm} />);
    const input = screen.getByPlaceholderText('Search through thousands of movies');
    await user.type(input, 'a');
    expect(setSearchTerm).toHaveBeenCalledWith('a');
  });

  it('should call setSearchTerm with the new value on change event', () => {
    render(<Search searchTerm="" setSearchTerm={setSearchTerm} />);
    const input = screen.getByPlaceholderText('Search through thousands of movies');
    fireEvent.change(input, { target: { value: 'matrix' } });
    expect(setSearchTerm).toHaveBeenCalledWith('matrix');
  });

  it('should call setSearchTerm with an empty string when the input is cleared', async () => {
    const user = userEvent.setup();
    render(<Search searchTerm="abc" setSearchTerm={setSearchTerm} />);
    const input = screen.getByPlaceholderText('Search through thousands of movies');
    await user.clear(input);
    expect(setSearchTerm).toHaveBeenCalledWith('');
  });

  it('should remain controlled and not change displayed value unless the prop changes', async () => {
    const user = userEvent.setup();
    const { rerender } = render(<Search searchTerm="orig" setSearchTerm={setSearchTerm} />);
    const input = screen.getByPlaceholderText('Search through thousands of movies');
    await user.type(input, 'x');
    expect(setSearchTerm).toHaveBeenCalled();
    expect(input).toHaveValue('orig');

    rerender(<Search searchTerm="updated" setSearchTerm={setSearchTerm} />);
    expect(input).toHaveValue('updated');
  });

  it('should render an empty input when searchTerm is an empty string', () => {
    render(<Search searchTerm="" setSearchTerm={setSearchTerm} />);
    expect(screen.getByPlaceholderText('Search through thousands of movies')).toHaveValue('');
  });
});